// Expose the wrapper module
// Include the raw bindings generated by `bindgen`
pub mod bindings;
pub mod ramulator_wrapper;

// Optionally re-export types or structs for external use
pub use ramulator_wrapper::RamulatorWrapperRs;

#[test]
fn main() {
    let config_path = "/usr/scratch/anazareth8/ramulator2/example_config.yaml";
    let ramulator = RamulatorWrapperRs::new(config_path);
    println!("Hello, world!");
}